# Generated by Django 4.0.3 on 2022-04-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume', to='main.volume', verbose_name='Объем'),
        ),
    ]
